import { Container } from '@chakra-ui/react'
import Head from 'next/head'

export const Layout = ({ children }) => {
  return (
    <Container m="0" mb="3rem" className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nextBosyuIcon.png" />
      </Head>

      {children}
    </Container>
  );
};
