import Head from 'next/head'
import gql from 'graphql-tag';
import { useQuery } from '@apollo/client';
import { Button } from "@chakra-ui/react"
import axios from 'axios';
import { signIn, signOut, useSession } from "next-auth/client";
import { useEffect } from 'react';

export default function Home() {
  const [session, sessionLoading] = useSession();

  console.log('session user is ', session?.user);

  useEffect(() => {
    axios.post(`${process.env.NEXT_PUBLIC_BACKEND_URL}/login`, { user: session?.user })
  }, [session, sessionLoading]);


  // MEMO: ここのファイルをもう少し整理したい
  // TODO: Figmaみたいなツールを使ってデザインカンプを作成したい
  const fetchUsers = gql`
    query {
      users {
        id,
        email,
        loginWay,
        lastName,
        firstName,
      }
    }
`;

  const { loading, error, data: users } = useQuery(fetchUsers);

  // { headers: {
  //   'X-Requested-With': 'XMLHttpRequest',
  // }},
  // { withCredentials: true }

  if (loading || sessionLoading) return <p>Loading...</p>;
  if (error) return <p>エラーが発生しました。エラーの詳細：{error?.message}</p>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./head_image.png" />
      </Head>

      <div>
        <Button onClick={() => signIn()}>Twitter Login</Button>
        <Button onClick={() => signOut()}>Twitter Logout</Button>
        {users?.users.map((user, key) => {
          return (
            <div key={key}>
              <div>login way: {user.loginWay}</div>
              <div>last name: {user.lastName}</div>
              <div>first name: {user.firstName}</div>
              <br />
            </div>
          )
        })}
      </div>
    </div>
  )
}
